name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Download Ren'Py
        run: wget https://www.renpy.org/dl/8.2.1/renpy-8.2.1-sdk.tar.bz2 && tar -xf renpy-8.2.1-sdk.tar.bz2
      - name: Find project folder
        run: |
          echo "Все папки game:"
          find . -name "game" -type d
          echo "---"
          echo "Ищем папку, в которой лежит script.rpy:"
          find . -name "script.rpy" -type f
      - name: Build APK
        run: |
          PROJECT=$(find . -name "script.rpy" -type f | head -1 | xargs dirname | xargs dirname)
          echo "Папка проекта: $PROJECT"
          cd renpy-8.2.1-sdk
          ./renpy.sh ../$PROJECT android
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-novel-apk
          path: "**/bin/*.apk"
